version: "3.7"

services:
  neo4j:
    image: neo4j:4.4.0-community
    container_name: my_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password1
    volumes:
      - ../ORION_graphs/NCATS_IFX_Odin/1dfd455abdbb7967/graph_1dfd455abdbb7967.db.dump:/tg_graph/db.dump
      - ./neo4j.conf:/conf/neo4j.conf
    tty: true
#    command:
#      - sh
#      - -c
#      - "neo4j-admin load --from=/tg_graph/db.dump --database=neo4j --force && neo4j start && bash"